[workspace]
resolver = "3"
members = [
    "services/desktop",
    "services/search",
    "services/mxsearch",
    "services/conf",
    "services/system",
    "shell/launcher",
    "shell/keyboard",
    "shell/notification",
    "dbus/freedesktop/bluez",
    "dbus/freedesktop/networkmanager",
    "dbus/freedesktop/pulseaudio",
    "dbus/freedesktop/upower",
    "dbus/mechanix/mxconf",
]

[workspace.package]
version = "0.0.0"
authors = [
    "Akshay Raina <akshayr@mechasystems.com>", 
    "Shoaib Merchant <shoaibm@mechasystems.com>"
]
edition = "2021"
license = "MIT"
repository = "https://github.com/mecha-org/mechanix-gui"
homepage = "https://mecha.so"
categories = ["gui"]
keywords = ["linux", "shell", "mobile", "gui", "ui", "graphics", "interface", "widgets"]

[workspace.dependencies]
mxconf_dbus = { path = "dbus/mechanix/mxconf" }
