[package]
name = "bevy_wayland"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
lazy_static = "1.5.0"
raw-window-handle = "0.6.2"
smithay-client-toolkit = "0.20.0"
wayland-backend = { version = "0.3.11", features = ["client_system"] }
